// ApiEndpoints.js
export const AUTH_ENDPOINT = "/Auth";
export const USERS_ENDPOINT = "/Users";
export const GET_LIST_ENDPOINT = "/GetList/getlist";
export const REGISTER_ENDPOINT = `${AUTH_ENDPOINT}/register`;
export const USER_DELETE_ENDPOINT = `${USERS_ENDPOINT}/Delete/delete`

export const BLOG_ENDPOINT = "/Blogs";
export const BLOG_GET_LIST_ENDPOINT = `${BLOG_ENDPOINT}/getlist`;
export const BLOG_DELETE_ENDPOINT = `${BLOG_ENDPOINT}/delete`;
export const BLOG_ADD_ENDPOINT = `${BLOG_ENDPOINT}/add`;
export const BLOG_UPDATE_ENDPOINT = `${BLOG_ENDPOINT}/update`;

export const IMAGE_ENDPOINT = "/Images";
export const IMAGE_GET_LIST_ENDPOINT = `${IMAGE_ENDPOINT}/getList`;
export const IMAGE_DELETE_ENDPOINT = `${IMAGE_ENDPOINT}/delete`;
export const IMAGE_ADD_ENDPOINT = `${IMAGE_ENDPOINT}/add`;

export const BLOGSPRESS_ENDPOINT = "/BlogsPress";
export const BLOGSPRESS_ADD_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/add`;
export const BLOGSPRESS_GET_LIST_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/getList`;
export const BLOGSPRESS_DELETE_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/delete`;
export const BLOGPRESS_UPDATE_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/update`;

export const NOTIFICATIONS_ENDPOINT = "/Notifications";
export const NOTIFICATIONS_ADD_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/add`;
export const NOTIFICATIONS_UPDATE_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/update`;
export const NOTIFICATIONS_DELETE_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/delete`;
export const NOTIFICATIONS_GETLIST_ENDPOINT= `${NOTIFICATIONS_ENDPOINT}/getList`;

export const ADMIN_NOTIFICATIONS_ENDPOINT = "/Notifications";
export const ADMIN_NOTIFICATIONS_ADD_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/add`;
export const ADMIN_NOTIFICATIONS_UPDATE_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/update`;
export const ADMIN_NOTIFICATIONS_DELETE_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/delete`;
export const ADMIN_NOTIFICATIONS_GETLIST_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/getList`;

export const INSTRUCTORS_ENDPOINT = "/Instructors";
export const INSTRUCTORS_GETLIST_ENDPOINT = `${INSTRUCTORS_ENDPOINT}/getList`;
export const INSTRUCTORS_DELETE_ENDPOINT = `${INSTRUCTORS_ENDPOINT}/delete`;

export const AUTH_INSTRUCTOR_ENDPOINT = "/AuthInstructor";
export const AUTH_INSTRUCTOR_REGISTER_ENDPOINT = `${AUTH_INSTRUCTOR_ENDPOINT}/register`;

export const EMPLOYEE_ENDPOINT = "/Employee";
export const EMPLOYEE_GETLIST_ENDPOINT = `${EMPLOYEE_ENDPOINT}/getList`;
export const EMPLOYEE_DELETE_ENDPOINT = `${EMPLOYEE_ENDPOINT}/delete`;

export const AUTH_EMPLOYEE_ENDPOINT = "/AuthEmployee";
export const AUTH_EMPLOYEE_REGISTER_ENDPOINT = `${AUTH_EMPLOYEE_ENDPOINT}/register`; 









