// ApiEndpoints.js
export const AUTH_ENDPOINT = "/Auth";
export const USERS_ENDPOINT = "/Users";
export const GET_LIST_ENDPOINT = "/GetList/getlist";
export const REGISTER_ENDPOINT = `${AUTH_ENDPOINT}/register`;
export const USER_DELETE_ENDPOINT = `${USERS_ENDPOINT}/Delete/delete`;

export const BLOG_ENDPOINT = "/Blogs";
export const BLOG_GET_LIST_ENDPOINT = `${BLOG_ENDPOINT}/getlist`;
export const BLOG_DELETE_ENDPOINT = `${BLOG_ENDPOINT}/delete`;
export const BLOG_ADD_ENDPOINT = `${BLOG_ENDPOINT}/add`;
export const BLOG_UPDATE_ENDPOINT = `${BLOG_ENDPOINT}/update`;

export const IMAGE_ENDPOINT = "/Images";
export const IMAGE_GET_LIST_ENDPOINT = `${IMAGE_ENDPOINT}/getList`;
export const IMAGE_DELETE_ENDPOINT = `${IMAGE_ENDPOINT}/delete`;
export const IMAGE_ADD_ENDPOINT = `${IMAGE_ENDPOINT}/add`;

export const BLOGSPRESS_ENDPOINT = "/BlogsPress";
export const BLOGSPRESS_ADD_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/add`;
export const BLOGSPRESS_GET_LIST_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/getList`;
export const BLOGSPRESS_DELETE_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/delete`;
export const BLOGPRESS_UPDATE_ENDPOINT = `${BLOGSPRESS_ENDPOINT}/update`;

export const NOTIFICATIONS_ENDPOINT = "/Notifications";
export const NOTIFICATIONS_ADD_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/add`;
export const NOTIFICATIONS_UPDATE_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/update`;
export const NOTIFICATIONS_DELETE_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/delete`;
export const NOTIFICATIONS_GETLIST_ENDPOINT = `${NOTIFICATIONS_ENDPOINT}/getList`;

export const ADMIN_NOTIFICATIONS_ENDPOINT = "/Notifications";
export const ADMIN_NOTIFICATIONS_ADD_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/add`;
export const ADMIN_NOTIFICATIONS_UPDATE_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/update`;
export const ADMIN_NOTIFICATIONS_DELETE_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/delete`;
export const ADMIN_NOTIFICATIONS_GETLIST_ENDPOINT = `${ADMIN_NOTIFICATIONS_ENDPOINT}/getList`;

export const INSTRUCTORS_ENDPOINT = "/Instructors";
export const INSTRUCTORS_GETLIST_ENDPOINT = `${INSTRUCTORS_ENDPOINT}/getList`;
export const INSTRUCTORS_DELETE_ENDPOINT = `${INSTRUCTORS_ENDPOINT}/delete`;

export const AUTH_INSTRUCTOR_ENDPOINT = "/AuthInstructor";
export const AUTH_INSTRUCTOR_REGISTER_ENDPOINT = `${AUTH_INSTRUCTOR_ENDPOINT}/register`;

export const EMPLOYEE_ENDPOINT = "/Employee";
export const EMPLOYEE_GETLIST_ENDPOINT = `${EMPLOYEE_ENDPOINT}/getList`;
export const EMPLOYEE_DELETE_ENDPOINT = `${EMPLOYEE_ENDPOINT}/delete`;

export const AUTH_EMPLOYEE_ENDPOINT = "/AuthEmployee";
export const AUTH_EMPLOYEE_REGISTER_ENDPOINT = `${AUTH_EMPLOYEE_ENDPOINT}/register`;

export const CONTACT_INFORMATIONS_ENDPOINT = "/ContactInformations";
export const CONTACT_INFORMATIONS_GETLIST_ENDPOINT = `${CONTACT_INFORMATIONS_ENDPOINT}/getList`;
export const CONTACT_INFORMATIONS_UPDATE_ENDPOINT = `${CONTACT_INFORMATIONS_ENDPOINT}/update`;

export const EXPERIENCES_ENDPOINT = "/Experiences";
export const EXPERIENCES_ADD_ENDPOINT = `${EXPERIENCES_ENDPOINT}/add`;

export const EXAMS_ENDPOINT = "/Exams";
export const EXAMS_ADD_ENDPOINT = `${EXAMS_ENDPOINT}/add`;
export const EXAMS_GET_LIST = `${EXAMS_ENDPOINT}/getlist`;
export const EXAM_DELETE = `${EXAMS_ENDPOINT}/delete`;

export const CERTIFICATE_ENDPOINT = "/Certificates";
export const CERTIFICATE_ADD_ENDPOINT = `${CERTIFICATE_ENDPOINT}/add`;
export const CERTIFICATE_GETLIST_ENDPOINT = `${CERTIFICATE_ENDPOINT}/getList`;
export const CERTIFICATE_DELETE_ENDPOINT = `${CERTIFICATE_ENDPOINT}/delete`;

export const SOCIAL_MEDIA_ENDPOINT = "/SocialMedias";
export const SOCIAL_MEDIA_ADD_ENDPOINT = `${SOCIAL_MEDIA_ENDPOINT}/add`;
export const SOCIAL_MEDIA_DELETE_ENDPOINT = `${SOCIAL_MEDIA_ENDPOINT}/delete`;
export const SOCIAL_MEDIA_GETLIST_ENDPOINT = `${SOCIAL_MEDIA_ENDPOINT}/getList`;

export const USER_SOCIAL_ENDPOINT = "/UserSocials";
export const USER_SOCIAL_ADD_ENDPOINT = `${USER_SOCIAL_ENDPOINT}/add`;
export const USER_SOCIAL_DELETE_ENDPOINT = `${USER_SOCIAL_ENDPOINT}/delete`;
export const USER_SOCIAL_GETLIST_ENDPOINT = `${USER_SOCIAL_ENDPOINT}/getList`;

export const FOREIGN_LANGUAGE_ENDPOINT = "/ForeignLanguages";
export const FOREIGN_LANGUAGE_ADD_ENDPOINT = `${FOREIGN_LANGUAGE_ENDPOINT}/add`;
export const FOREIGN_LANGUAGE_DELETE_ENDPOINT = `${FOREIGN_LANGUAGE_ENDPOINT}/delete`;
export const FOREIGN_LANGUAGE_GETLIST_ENDPOINT = `${FOREIGN_LANGUAGE_ENDPOINT}/getlist`;

export const FOREIGN_LANGUAGE_LEVEL_ENDPOINT = "/ForeignLanguageLevels";
export const FOREIGN_LANGUAGE_LEVEL_ADD_ENDPOINT = `${FOREIGN_LANGUAGE_LEVEL_ENDPOINT}/add`;
export const FOREIGN_LANGUAGE_LEVEL_DELETE_ENDPOINT = `${FOREIGN_LANGUAGE_LEVEL_ENDPOINT}/delete`;
export const FOREIGN_LANGUAGE_LEVEL_GETLIST_ENDPOINT = `${FOREIGN_LANGUAGE_LEVEL_ENDPOINT}/getlist`;

export const USER_LANGUAGE_ENDPOINT = "/UserLanguages";
export const USER_LANGUAGE_ADD_ENDPOINT = `${USER_LANGUAGE_ENDPOINT}/add`;
export const USER_LANGUAGE_DELETE_ENDPOINT = `${USER_LANGUAGE_ENDPOINT}/delete`;
export const USER_LANGUAGE_GETLIST_BY_USER_ENDPOINT = `${USER_LANGUAGE_ENDPOINT}/getListByUser`;
