
const courseData = [
  {
    id: 1,
    image: "https://picsum.photos/id/237/200/200",
    teacher: "John Doe",
    duration: "10:22",
    subject: "C#",
  },
  {
    id: 2,
    image: "https://picsum.photos/id/238/200/200",
    teacher: "Gürkan İlişen",
    duration: "8:15",
    subject: "Profesyonel Gelişim Eğitimleri",
  },
  {
    id: 3,
    image: "https://picsum.photos/id/239/200/200",
    teacher: "Jane Doe",
    duration: "6:45",
    subject: "Çeşitlilik ve Kapsayıcılık",
  },
  {
    id: 4,
    image: "https://picsum.photos/id/61/200/200",
    teacher: "Jane Doe",
    duration: "7:30",
    subject: "Sunum Becerileri",
  },
  {
    id: 5,
    image: "https://picsum.photos/id/231/200/200",
    teacher: "Jane Doe",
    duration: "9:00",
    subject: "Başarı ve Sonuç Odaklılık",
  },
  {
    id: 6,
    image: "https://picsum.photos/id/232/200/200",
    teacher: "Jane Doe",
    duration: "5:45",
    subject: "Takım Bilinci",
  },
  {
    id: 7,
    image: "https://picsum.photos/id/233/200/200",
    teacher: "Jane Doe",
    duration: "8:30",
    subject: "Etkili İletişim ve İlişki Yönetimi",
  },
  {
    id: 8,
    image: "https://picsum.photos/id/234/200/200",
    teacher: "Jane Doe",
    duration: "6:15",
    subject: "Karar Verme",
  },
  {
    id: 9,
    image: "https://picsum.photos/id/235/200/200",
    teacher: "Jane Doe",
    duration: "7:45",
    subject: "Profesyonellik",
  },
  {
    id: 10,
    image: "https://picsum.photos/id/236/200/200",
    teacher: "Jane Doe",
    duration: "8:00",
    subject: "Kişisel Motivasyon",
  },
  {
    id: 11,
    image: "https://picsum.photos/id/237/200/200",
    teacher: "John Doe",
    duration: "10:22",
    subject: "Problem Çözme",
  },
  {
    id: 12,
    image: "https://picsum.photos/id/238/200/200",
    teacher: "Gürkan İlişen",
    duration: "8:15",
    subject: "Yenilikçilik ve Yaratıcılık",
  },
  {
    id: 13,
    image: "https://picsum.photos/id/239/200/200",
    teacher: "Jane Doe",
    duration: "6:30",
    subject: "Verimlilik ve Zaman Yönetimi",
  },
  {
    id: 14,
    image: "https://picsum.photos/id/61/200/200",
    teacher: "Jane Doe",
    duration: "7:15",
    subject: "Müzakere Becerileri",
  },
  {
    id: 15,
    image: "https://picsum.photos/id/231/200/200",
    teacher: "Jane Doe",
    duration: "9:30",
    subject: "Duygusal Zeka",
  },
  {
    id: 16,
    image: "https://picsum.photos/id/232/200/200",
    teacher: "Jane Doe",
    duration: "5:15",
    subject: "Çevik Düşünme",
  },
  {
    id: 17,
    image: "https://picsum.photos/id/233/200/200",
    teacher: "Jane Doe",
    duration: "8:45",
    subject: "Esneklik",
  },
  {
    id: 18,
    image: "https://picsum.photos/id/234/200/200",
    teacher: "Jane Doe",
    duration: "6:00",
    subject: "Sürekli Gelişim",
  },
  {
    id: 19,
    image: "https://picsum.photos/id/235/200/200",
    teacher: "Jane Doe",
    duration: "7:30",
    subject: "Ticari Odaklılık",
  },
  {
    id: 20,
    image: "https://picsum.photos/id/236/200/200",
    teacher: "Jane Doe",
    duration: "8:15",
    subject: "Çatışma Çözme",
  },
  {
    id: 21,
    image: "https://picsum.photos/id/237/200/200",
    teacher: "John Doe",
    duration: "10:00",
    subject: "Azim ve Direnç",
  },
  {
    id: 22,
    image: "https://picsum.photos/id/238/200/200",
    teacher: "Gürkan İlişen",
    duration: "9:45",
    subject: "Proaktif Olma",
  },
  {
    id: 23,
    image: "https://picsum.photos/id/239/200/200",
    teacher: "Jane Doe",
    duration: "6:15",
    subject: "Kariyer Yönetimi",
  },
  {
    id: 24,
    image: "https://picsum.photos/id/61/200/200",
    teacher: "Jane Doe",
    duration: "7:30",
    subject: "Stres Yönetimi",
  },
  {
    id: 25,
    image: "https://picsum.photos/id/231/200/200",
    teacher: "Jane Doe",
    duration: "8:45",
    subject: "Kritik Düşünme",
  },
  {
    id: 26,
    image: "https://picsum.photos/id/232/200/200",
    teacher: "Jane Doe",
    duration: "5:30",
    subject: "Kişisel Güç ve Güvenilirlik",
  },
  {
    id: 27,
    image: "https://picsum.photos/id/233/200/200",
    teacher: "Jane Doe",
    duration: "9:15",
    subject: "Özdisiplin",
  },
  {
    id: 28,
    image: "https://picsum.photos/id/234/200/200",
    teacher: "Jane Doe",
    duration: "6:30",
    subject: "Programlama",
  },
  {
    id: 29,
    image: "https://picsum.photos/id/235/200/200",
    teacher: "Jane Doe",
    duration: "7:45",
    subject: "Yazılım Geliştirme",
  },
  {
    id: 30,
    image: "https://picsum.photos/id/236/200/200",
    teacher: "Jane Doe",
    duration: "8:00",
    subject: "Finansta Mükemmellik",
  },
  {
    id: 31,
    image: "https://picsum.photos/id/237/200/200",
    teacher: "John Doe",
    duration: "10:22",
    subject: "IK' da Mükemmellik",
  },
  {
    id: 32,
    image: "https://picsum.photos/id/238/200/200",
    teacher: "Gürkan İlişen",
    duration: "8:15",
    subject: "Bilişim Teknolojileri",
  },
  {
    id: 33,
    image: "https://picsum.photos/id/239/200/200",
    teacher: "Jane Doe",
    duration: "6:45",
    subject: "İş İngilizcesi",
  },
  {
    id: 34,
    image: "https://picsum.photos/id/61/200/200",
    teacher: "Jane Doe",
    duration: "7:30",
    subject: "Sigortacılıkta Mükemmellik",
  },
  {
    id: 35,
    image: "https://picsum.photos/id/231/200/200",
    teacher: "Jane Doe",
    duration: "9:00",
    subject: "Müşteri Duyarlılık",
  },
  {
    id: 36,
    image: "https://picsum.photos/id/232/200/200",
    teacher: "Jane Doe",
    duration: "5:45",
    subject: "Proje Yönetimi",
  },
  {
    id: 37,
    image: "https://picsum.photos/id/233/200/200",
    teacher: "Jane Doe",
    duration: "8:30",
    subject: "Ekip Yönetimi",
  },
  {
    id: 38,
    image: "https://picsum.photos/id/234/200/200",
    teacher: "Jane Doe",
    duration: "6:15",
    subject: "Stratejik Düşünme",
  },
  {
    id: 39,
    image: "https://picsum.photos/id/235/200/200",
    teacher: "Jane Doe",
    duration: "7:45",
    subject: "Liderlikte İletişim",
  },
  {
    id: 40,
    image: "https://picsum.photos/id/236/200/200",
    teacher: "Jane Doe",
    duration: "8:15",
    subject: "UI/UX Tasarımı",
  },
  {
    id: 41,
    image: "https://picsum.photos/id/237/200/200",
    teacher: "John Doe",
    duration: "10:00",
    subject: "VUCA Dünyası",
  },
  {
    id: 42,
    image: "https://picsum.photos/id/238/200/200",
    teacher: "Gürkan İlişen",
    duration: "9:45",
    subject: "Dijital Dünyada Sosyal Medya İletişimi",
  },
  {
    id: 43,
    image: "https://picsum.photos/id/239/200/200",
    teacher: "Jane Doe",
    duration: "6:15",
    subject: "Büyük Veri",
  },
  {
    id: 44,
    image: "https://picsum.photos/id/61/200/200",
    teacher: "Jane Doe",
    duration: "7:30",
    subject: "Dijital Dönüşüm",
  },
  {
    id: 45,
    image: "https://picsum.photos/id/231/200/200",
    teacher: "Jane Doe",
    duration: "8:45",
    subject: "Dijital Okuryazarlık",
  },
  {
    id: 46,
    image: "https://picsum.photos/id/232/200/200",
    teacher: "Jane Doe",
    duration: "5:30",
    subject: "Sürdürülebilirlik",
  },
  {
    id: 47,
    image: "https://picsum.photos/id/233/200/200",
    teacher: "Jane Doe",
    duration: "9:15",
    subject: "Mutluluk",
  },
  {
    id: 48,
    image: "https://picsum.photos/id/234/200/200",
    teacher: "Jane Doe",
    duration: "6:30",
    subject: "Kişisel Gelişim",
  },
];

  export const getCourseData = () => {
    return Promise.resolve(courseData);
  };